window.dashboardData = {
  "events": [
    {
      "key": "gia",
      "name": "GIVE IT ALL",
      "date": "2026-07-23",
      "tag": "gia-16-buyer",
      "tiers": [
        {
          "tag": "gia-16-buyer",
          "label": "Single",
          "tickets_per_contact": 1,
          "buyers": 28,
          "tickets": 28
        },
        {
          "tag": "gia-16-4pack",
          "label": "4-Pack",
          "tickets_per_contact": 4,
          "buyers": 0,
          "tickets": 0
        }
      ],
      "both_buyers": 0,
      "tickets_total": 29,
      "buyers_total": 28,
      "total_paid": 909.05,
      "csv": "gia-attendees.csv",
      "roster": {
        "buyers": [
          {
            "role": "Buyer",
            "name": "adam tillner-smith",
            "email": "adam.tillner.smith@hotmail.co.uk",
            "phone": "+447540274609",
            "whatsapp": "+447540274609",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-16-buyer, attending-next-event, gia-bali, gia-2-buyer, lead - community signup, member, profile-complete",
            "ghl_contact_id": "BtSm5svfZarBsvV20MeT",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "ajay prashad",
            "email": "prashadajay80@gmail.com",
            "phone": "+61407435397",
            "whatsapp": "+61407435397",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "profile-complete, gia-16-buyer, attending-next-event, lead - community signup, member",
            "ghl_contact_id": "cjTnhraNdpYLs7Qu3opx",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "aline abrouk",
            "email": "abrouk.aline@gmail.com",
            "phone": "+32494826429",
            "whatsapp": "+32494826429",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "lead - community signup, member, gia-16-buyer, attending-next-event",
            "ghl_contact_id": "Wo30xxwwLFkF3gVtenpi",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "ana clara meira pascual",
            "email": "anaclarameirap@gmail.com",
            "phone": "+5511959158831",
            "whatsapp": "+5511959158831",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-16-buyer, attending-next-event, lead - community signup, member",
            "ghl_contact_id": "GQHMbFep5YpE26tYsub7",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "angelina cosenza",
            "email": "coosenza@web.de",
            "phone": "+4917670855134",
            "whatsapp": "+4917670855134",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-16-buyer, attending-next-event",
            "ghl_contact_id": "ctqGfUCtrfhmSkWaBnvR",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "daria topic",
            "email": "topic.d@hotmail.hu",
            "phone": "+447707968481",
            "whatsapp": "+447707968481",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "speaker - bali, women, gia-15-buyer, lead - community signup, member, profile-complete, unsubscribed, gia-16-buyer, attending-next-event",
            "ghl_contact_id": "GM4BmHakJ5a7Dubyt6V5",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "diogo travanca",
            "email": "travancadiogo@gmail.com",
            "phone": "+351939101155",
            "whatsapp": "+351939101155",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-16-buyer, attending-next-event, lead - community signup, member, profile-complete",
            "ghl_contact_id": "Eti3gnlI4Q4z6GSxYGw2",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "dustin rivet",
            "email": "dustinrivet@gmail.com",
            "phone": "+94741232893",
            "whatsapp": "+94741232893",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-2-buyer, gia-7-buyer, reconnected man, gia-16-buyer, attending-next-event, lead - community signup, member, profile-complete",
            "ghl_contact_id": "EpzckhvaDtHA7BBM8ENS",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "halyna rivet",
            "email": "halynamukomol@gmail.com",
            "phone": "+353832067534",
            "whatsapp": "+353832067534",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-2-buyer, women, gia-16-buyer, attending-next-event, lead - community signup, member",
            "ghl_contact_id": "fqPlpduGoQzD6DiED4x8",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "hanna peters",
            "email": "hannafresha123@gmail.com",
            "phone": "+61401339320",
            "whatsapp": "+61401339320",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-16-buyer, attending-next-event, lead - community signup, member",
            "ghl_contact_id": "AI6j4iNRBTqApNtEhbgx",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "jessica seruno",
            "email": "jessica.seruno@gmail.com",
            "phone": "+33646414880",
            "whatsapp": "+33646414880",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-15-buyer, speaker - bali, gia-16-buyer, attending-next-event",
            "ghl_contact_id": "XDLeah9za3k5xYIx2zUd",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "job baltes",
            "email": "jobbaltes@icloud.com",
            "phone": "+31637219162",
            "whatsapp": "+31637219162",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-12-buyer, founders_breakfast, speaker - bali, gia-13-buyer, fb02, lead - community signup, member, gia-14-buyer, fb03, gia15+fb04, gia-15-buyer, fb04, fb05, gia-16-buyer, attending-next-event",
            "ghl_contact_id": "jqAxFdk7W7YxEZvX7gGh",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "joshua king",
            "email": "joshdavidking@gmail.com",
            "phone": "+14694149232",
            "whatsapp": "+14694149232",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-16-buyer, attending-next-event",
            "ghl_contact_id": "XEnRNhosuVFKXQdNdHyP",
            "tier": "Single",
            "tickets": 2,
            "guest_capacity": 1,
            "guests": [
              {
                "role": "Guest",
                "name": "joshua king (+1)",
                "email": "",
                "phone": "",
                "whatsapp": "",
                "attendee_type": "",
                "booked_by": "",
                "guest_of": "joshua king",
                "booked": true,
                "profile": false,
                "member": false,
                "tags": "extra-ticket",
                "ghl_contact_id": ""
              }
            ],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "julian picklapp",
            "email": "jpicklapp@web.de",
            "phone": "+491715104730",
            "whatsapp": "+491715104730",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-16-buyer, attending-next-event, lead - community signup, member",
            "ghl_contact_id": "FKPbgDusjvqINWLRKOWx",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "kat averkamp",
            "email": "kataverkamp@gmail.com",
            "phone": "+16195359409",
            "whatsapp": "+16195359409",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-16-buyer, attending-next-event, lead - community signup, member, profile-complete",
            "ghl_contact_id": "ESX2neH5SWjgXf2zDM8k",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "ken wira",
            "email": "wira.ken@gmail.com",
            "phone": "+4917623841139",
            "whatsapp": "+4917623841139",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "profile-complete, member, gia-14-buyer, gia-16-buyer, attending-next-event, gia-bali",
            "ghl_contact_id": "bXC8KkYKWs7OqpbDkPUa",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "laura-marie casey",
            "email": "lauramarie.casey@icloud.com",
            "phone": "+34663984740",
            "whatsapp": "+34663984740",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "women, gia-15-buyer, lead - community signup, member, profile-complete, gia-16-buyer, attending-next-event",
            "ghl_contact_id": "Hg4uwCurcBWOEnewG40a",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "lawrence linker",
            "email": "lawrencelinker@gmail.com",
            "phone": "+6594241346",
            "whatsapp": "+6594241346",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-13-buyer, unsubscribed, gia-16-buyer, attending-next-event",
            "ghl_contact_id": "BpX8ZTXb8rWMWfzCGxx1",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "lukas seerup nielsen",
            "email": "lukas@wearespace.dk",
            "phone": "+628113703215",
            "whatsapp": "+628113703215",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-15-buyer, fb04, gia-16-buyer, attending-next-event",
            "ghl_contact_id": "PdAvLes6EXuSJmYBpHfv",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "l\u00e9na delahaye",
            "email": "delahaye.lena1@gmail.com",
            "phone": "+6287841443788",
            "whatsapp": "+6287841443788",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-16-buyer, attending-next-event",
            "ghl_contact_id": "RMdQve5wOpR786issz6x",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "mitchell o'callaghan",
            "email": "mitchhaydenocallaghan@gmail.com",
            "phone": "+447794118543",
            "whatsapp": "+447794118543",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-15-buyer, profile-complete, member, speaker - bali, gia-16-buyer, attending-next-event",
            "ghl_contact_id": "cyIDTYuwKgvWw8NUPuGX",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "nathan aherne",
            "email": "nathan@nathanaherne.com",
            "phone": "+61402555080",
            "whatsapp": "+61402555080",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-11-buyer, gia-13-buyer, gia+founders_breakfast, speaker - bali, gia-16-buyer, attending-next-event",
            "ghl_contact_id": "1PNOEwhVyr7dJ3BmB50c",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "nikol toncheva",
            "email": "nikol.toncheva15@gmail.com",
            "phone": "+6282147387279",
            "whatsapp": "+6282147387279",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-15-buyer, lead - community signup, member, gia-16-buyer, attending-next-event",
            "ghl_contact_id": "Qp8RL9VcKL0p6mNym2wq",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "peter meglis",
            "email": "mailmeglis@gmail.com",
            "phone": "+19787585623",
            "whatsapp": "+19787585623",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "profile-complete, member, gia-14-buyer, gia-15-buyer, speaker - bali, gia-16-buyer, attending-next-event",
            "ghl_contact_id": "SgGyjE5vQMQUjoDOmVMw",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "polina valerieva petrova",
            "email": "polinafitkitchen@gmail.com",
            "phone": "+447588687034",
            "whatsapp": "+447588687034",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-16-buyer, attending-next-event, lead - community signup, member, profile-complete",
            "ghl_contact_id": "SL1Vw7meOOfhEYk82WWK",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "ree f",
            "email": "shiree.francis@outlook.com",
            "phone": "+447475123637",
            "whatsapp": "+447475123637",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-2-buyer, gia-3-buyer, gia-4-buyer, gia-5-buyer, women, gia-16-buyer, attending-next-event, lead - community signup, member",
            "ghl_contact_id": "6I86ab9NXyfpLnk4QQJC",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "rory callaghan",
            "email": "rdkcallaghan@gmail.com",
            "phone": "+6281339849367",
            "whatsapp": "+6281339849367",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "speaker - bali, gia-16-buyer, attending-next-event",
            "ghl_contact_id": "H26uBtsKNqbZeNnQG91I",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "serena spink",
            "email": "serena@serenaspink.com",
            "phone": "+447511404769",
            "whatsapp": "+447511404769",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-15-buyer, gia15+fb04, fb04, lead - community signup, member, profile-complete, gia-16-buyer, attending-next-event, opted-in newsletter, speaker - bali",
            "ghl_contact_id": "ElNGRtO2LLnf8b4qfgyF",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          }
        ],
        "unassigned_guests": [],
        "buyer_count": 28,
        "guest_slots_total": 1,
        "guests_booked": 1,
        "headcount": 29,
        "manual_adjustment_total": 0,
        "manual_adjustments": [],
        "override_delta": 0
      },
      "manual_adjustment_total": 0,
      "manual_adjustments": [],
      "guest_slot_override_delta": 0,
      "extra_tickets_total": 1
    },
    {
      "key": "fb",
      "name": "Founders Breakfast",
      "date": "2026-07-28",
      "tag": "fb05",
      "tiers": [
        {
          "tag": "fb05",
          "label": "Single",
          "tickets_per_contact": 1,
          "buyers": 1,
          "tickets": 1
        },
        {
          "tag": "fb05+1",
          "label": "+1 (2 tickets)",
          "tickets_per_contact": 2,
          "buyers": 0,
          "tickets": 0
        }
      ],
      "both_buyers": 0,
      "tickets_total": 1,
      "buyers_total": 1,
      "total_paid": 18.0,
      "csv": "fb-attendees.csv",
      "roster": null,
      "manual_adjustment_total": 0,
      "manual_adjustments": [],
      "guest_slot_override_delta": 0,
      "extra_tickets_total": 0
    }
  ],
  "both_tag": "gia16+fb05",
  "both_count": 0,
  "both_total_paid": 0,
  "both_csv": "both-events.csv",
  "stripe_enabled": true,
  "errors": [],
  "last_updated_iso": "2026-07-23T01:54:07.225849+00:00",
  "last_updated_local": "Thu 23 Jul 2026, 09:54 AM"
};
