window.dashboardData = {
  "events": [
    {
      "key": "gia",
      "name": "GIVE IT ALL",
      "date": "2026-08-20",
      "tag": "gia-17-buyer",
      "tiers": [
        {
          "tag": "gia-17-buyer",
          "label": "Single",
          "tickets_per_contact": 1,
          "buyers": 38,
          "tickets": 38
        },
        {
          "tag": "gia-17-4pack",
          "label": "4-Pack",
          "tickets_per_contact": 4,
          "buyers": 0,
          "tickets": 0
        }
      ],
      "both_buyers": 6,
      "tickets_total": 46,
      "buyers_total": 44,
      "total_paid": 1777.0,
      "csv": "gia-attendees.csv",
      "roster": {
        "buyers": [
          {
            "role": "Buyer",
            "name": "adam tillner-smith",
            "email": "adam.tillner.smith@hotmail.co.uk",
            "phone": "+447540274609",
            "whatsapp": "+447540274609",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-16-buyer, gia-2-buyer, lead - community signup, member, profile-complete, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "BtSm5svfZarBsvV20MeT",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "adriana velcheva",
            "email": "adichka2210@gmail.com",
            "phone": "+359898434404",
            "whatsapp": "+359898434404",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-17-buyer, attending-next-event, lead - community signup, member",
            "ghl_contact_id": "gaJqTF6KxcblmZBlCArU",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "ajay prashad",
            "email": "prashadajay80@gmail.com",
            "phone": "+61407435397",
            "whatsapp": "+61407435397",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "profile-complete, gia-16-buyer, lead - community signup, member, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "cjTnhraNdpYLs7Qu3opx",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "aline abrouk",
            "email": "abrouk.aline@gmail.com",
            "phone": "+32494826429",
            "whatsapp": "+32494826429",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "lead - community signup, member, gia-16-buyer, profile-complete, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "Wo30xxwwLFkF3gVtenpi",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "angelina cosenza",
            "email": "coosenza@web.de",
            "phone": "+4917670855134",
            "whatsapp": "+4917670855134",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "lead - community signup, member, profile-complete, gia-16-buyer, fb05, mens work, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "Nu1ISBpP6HWqGkXo3oun",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "ashley grossmann",
            "email": "ashleygrossmann@gmail.com",
            "phone": "+447775747209",
            "whatsapp": "+447775747209",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "archetypequizcompleted, archetype_freedomfortress, mens work, gia-13-buyer, gia-17-buyer, attending-next-event, lead - community signup, member",
            "ghl_contact_id": "F1BzxocPcU3JLAJDsIBB",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "brian siegal",
            "email": "briannathan545@gmail.com",
            "phone": "+17475772791",
            "whatsapp": "+17475772791",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "speaker - bali, gia-15-buyer, lead - community signup, member, gia17+fb06, fb06, gia-17-buyer, attending-next-event, profile-complete",
            "ghl_contact_id": "38PnoNIjkwWKPEXEvdFg",
            "tier": "Bundle (Both Events)",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "camila santiago",
            "email": "camilapsantiago@gmail.com",
            "phone": "+6281237890683",
            "whatsapp": "+6281237890683",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-5-buyer, women, lead - community signup, member, gia-17-buyer, attending-next-event, profile-complete",
            "ghl_contact_id": "L6uzIjYv8h7ruQahk2vp",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "chris diggle",
            "email": "chris@astrasolar.com.au",
            "phone": "+61434371831",
            "whatsapp": "+61434371831",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-17-buyer, attending-next-event",
            "ghl_contact_id": "1YaP3lJHiZswHuR4xVN2",
            "tier": "Single",
            "tickets": 2,
            "guest_capacity": 1,
            "guests": [
              {
                "role": "Guest",
                "name": "chris diggle (+1)",
                "email": "",
                "phone": "",
                "whatsapp": "",
                "attendee_type": "",
                "booked_by": "",
                "guest_of": "chris diggle",
                "booked": true,
                "profile": false,
                "member": false,
                "tags": "extra-ticket",
                "ghl_contact_id": ""
              }
            ],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "chris howard",
            "email": "ceobrandnew@gmail.com",
            "phone": "+14246537436",
            "whatsapp": "+14246537436",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "speaker - bali, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "M1WkTNvwif8UqzyuyMkI",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "dan halliday",
            "email": "d.halliday01@gmail.com",
            "phone": "+62817340280023",
            "whatsapp": "+62817340280023",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-4-buyer, unsubscribed, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "Gt5cZrVg20OPllMEtwKd",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "dominica ni wayan juni astrini",
            "email": "domi8greatlifes@gmail.com",
            "phone": "+6281529422856",
            "whatsapp": "+6281529422856",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-17-buyer, attending-next-event",
            "ghl_contact_id": "tgAWt6m01gq51gu5BYGz",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "dustin rivet",
            "email": "dustinrivet@gmail.com",
            "phone": "+94741232893",
            "whatsapp": "+94741232893",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-2-buyer, gia-7-buyer, reconnected man, gia-16-buyer, lead - community signup, member, profile-complete, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "EpzckhvaDtHA7BBM8ENS",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "felipe zuniga",
            "email": "felipegelatopastry@gmail.com",
            "phone": "+393515552450",
            "whatsapp": "+393515552450",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-17-buyer, attending-next-event, lead - community signup, member, profile-complete",
            "ghl_contact_id": "lWlqvA6WYdS3jm7VrlIb",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "fil biggs",
            "email": "fil@live.co.uk",
            "phone": "+447988936437",
            "whatsapp": "+447988936437",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": false,
            "tags": "gia-8-buyer, gia-9-buyer, archetypequizcompleted, archetype_intellectualdefender, mens work, speaker - bali, gia-10-buyer, gia-17-buyer, attending-next-event, profile-complete",
            "ghl_contact_id": "fXGrShe6XffebqQyeouT",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "hannah whelan",
            "email": "hannahwhelan4@gmail.com",
            "phone": "+353868634541",
            "whatsapp": "+353868634541",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-14-buyer, lead - community signup, member, women, gia-17-buyer, attending-next-event, profile-complete",
            "ghl_contact_id": "qcu5wC8VdJkQr2sByeaO",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "i gede eka cipta ariawan",
            "email": "ekacipta19@gmail.com",
            "phone": "+6282122191919",
            "whatsapp": "+6282122191919",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "lead - community signup, member, gia-17-buyer, attending-next-event, email bounced, profile-complete",
            "ghl_contact_id": "NldP0a4owWWJuT4Mnvmx",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "jessica eude seruno",
            "email": "jessica.seruno@gmail.com",
            "phone": "+33646414880",
            "whatsapp": "+33646414880",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-15-buyer, speaker - bali, gia-16-buyer, lead - community signup, member, profile-complete, gia-17-buyer, attending-next-event, opted-in newsletter",
            "ghl_contact_id": "XDLeah9za3k5xYIx2zUd",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "job baltes",
            "email": "jobbaltes@icloud.com",
            "phone": "+31637219162",
            "whatsapp": "+31637219162",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-12-buyer, founders_breakfast, speaker - bali, gia-13-buyer, fb02, lead - community signup, member, gia-14-buyer, fb03, gia15+fb04, gia-15-buyer, fb04, fb05, gia-16-buyer, gia17+fb06, fb06, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "jqAxFdk7W7YxEZvX7gGh",
            "tier": "Bundle (Both Events)",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "jordi mar\u00edn valle",
            "email": "jmv.jordi@gmail.com",
            "phone": "+34630615757",
            "whatsapp": "+34630615757",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-6-buyer, fulfillment alignment, speaker - bali, gia-8-buyer, gia-9-buyer, archetypequizcompleted, archetype_freedomfortress, mens work, reconnected man, gia-10-buyer, feedback received, founders_breakfast, gia-12-buyer, gia-13-buyer, member, profile-complete, gia-14-buyer, gia-15-buyer, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "0TbaMhgiEPT0fkSoLRSn",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "joshua king",
            "email": "joshdavidking@gmail.com",
            "phone": "+14694149232",
            "whatsapp": "+14694149232",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-17-buyer, attending-next-event",
            "ghl_contact_id": "XEnRNhosuVFKXQdNdHyP",
            "tier": "Single",
            "tickets": 2,
            "guest_capacity": 1,
            "guests": [
              {
                "role": "Guest",
                "name": "joshua king (+1)",
                "email": "",
                "phone": "",
                "whatsapp": "",
                "attendee_type": "",
                "booked_by": "",
                "guest_of": "joshua king",
                "booked": true,
                "profile": false,
                "member": false,
                "tags": "extra-ticket",
                "ghl_contact_id": ""
              }
            ],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "julia glazewska",
            "email": "juliaglazewska95@gmail.com",
            "phone": "+4552755716",
            "whatsapp": "+4552755716",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "founders_breakfast, fb02, lead - community signup, member, profile-complete, gia-14-buyer, women, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "p8jwQJrDezuvU8ZLQnzP",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "kellie kayser",
            "email": "kk_czar@yahoo.com",
            "phone": "+61405205305",
            "whatsapp": "+61405205305",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-10-buyer, women, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "DAYTIc2qQGoWTfh5AztF",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "ken wira",
            "email": "kenualom@gmail.com",
            "phone": "+4917623841139",
            "whatsapp": "+4917623841139",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "profile-complete, member, gia-14-buyer, gia-16-buyer, speaker - bali, priority audit, mens work, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "bXC8KkYKWs7OqpbDkPUa",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "kezia euodia",
            "email": "euodia0322@gmail.com",
            "phone": "+62818315943",
            "whatsapp": "+62818315943",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-1-buyer, unsubscribed, women, gia17+fb06, fb06, gia-17-buyer, attending-next-event, lead - community signup, member, profile-complete",
            "ghl_contact_id": "WhAsgWp6rsDTWfHTaOMN",
            "tier": "Bundle (Both Events)",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "lea baptista",
            "email": "leamarieteixeira@yahoo.de",
            "phone": "+491637377539",
            "whatsapp": "+491637377539",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "fb05, speaker - bali, gia-17-buyer, attending-next-event, lead - community signup, member, profile-complete",
            "ghl_contact_id": "LcaMG3ZLVdAEUfLFXnwN",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "leonie erenstein",
            "email": "hello@thelovelab.nl",
            "phone": "+31614581864",
            "whatsapp": "+31614581864",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "speaker - bali, gia-14-buyer, lead - community signup, member, profile-complete, women, gia17+fb06, fb06, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "HlWwAd4qFGPymxpBnZLd",
            "tier": "Bundle (Both Events)",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "luke anning",
            "email": "lanning84@googlemail.com",
            "phone": "+573011951296",
            "whatsapp": "+573011951296",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-7-buyer, fb06, gia-17-buyer, attending-next-event, speaker - bali",
            "ghl_contact_id": "uCnZL77Juw2krauYvXMU",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "mai kamouni",
            "email": "maikamouni@gmail.com",
            "phone": "+6282313556146",
            "whatsapp": "+6282313556146",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-17-buyer, attending-next-event, lead - community signup, member, profile-complete",
            "ghl_contact_id": "wwKANxJCHndmSjAE652z",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "mariya mihaylova",
            "email": "mariyamm@umich.edu",
            "phone": "+33783368174",
            "whatsapp": "+33783368174",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-17-buyer, attending-next-event, lead - community signup, member",
            "ghl_contact_id": "f8ytyXSs7eTYzc9KTNEJ",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "matthew kaos",
            "email": "matthewkingks@live.com",
            "phone": "+61429118275",
            "whatsapp": "+61429118275",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-17-buyer, attending-next-event, unsubscribed, lead - community signup, member",
            "ghl_contact_id": "rYOfpoHedVwx2Tlv24W5",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "nathan aherne",
            "email": "nathan@nathanaherne.com",
            "phone": "+61402555080",
            "whatsapp": "+61402555080",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-11-buyer, gia-13-buyer, gia+founders_breakfast, speaker - bali, gia-16-buyer, fb05, gia17+fb06, fb06, gia-17-buyer, attending-next-event, lead - community signup, member, profile-complete",
            "ghl_contact_id": "1PNOEwhVyr7dJ3BmB50c",
            "tier": "Bundle (Both Events)",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "palvi shah",
            "email": "palvishah1998@gmail.com",
            "phone": "+447500393239",
            "whatsapp": "+447500393239",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "lead - community signup, member, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "FjYgrhpndrjwoqOT2XuT",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "peter meglis",
            "email": "mailmeglis@gmail.com",
            "phone": "+19787585623",
            "whatsapp": "+19787585623",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "profile-complete, member, gia-14-buyer, gia-15-buyer, speaker - bali, gia-16-buyer, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "SgGyjE5vQMQUjoDOmVMw",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "ratih septivita",
            "email": "de_lavita@yahoo.co.uk",
            "phone": "+628129553534",
            "whatsapp": "+628129553534",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-10-buyer, lead - community signup, member, profile-complete, women, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "JLQyTVTN6pc4iCYgkrPr",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "renee lim",
            "email": "renee5sarah@gmail.com",
            "phone": "+61400244963",
            "whatsapp": "+61400244963",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "speaker - bali, gia-5-buyer, gia-8-buyer, gia-9-buyer, feedback 2, women, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "NinT5ubAovDX9qQEkIFa",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "rich nelson",
            "email": "truetargetcoaching@gmail.com",
            "phone": "+61431096112",
            "whatsapp": "+61431096112",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-14-buyer, fb03, lead - community signup, member, profile-complete, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "tgn0AdKe8U3dmwRiRJQf",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "robert hangu",
            "email": "robert@nextops.agency",
            "phone": "+34602441540",
            "whatsapp": "+34602441540",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "member, profile-complete, lead - community signup, speaker - bali, gia-14-buyer, gia-15-buyer, gia17+fb06, fb06, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "ITcKTNMqscUVvET3L9C7",
            "tier": "Bundle (Both Events)",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "ryan herrington",
            "email": "ryan@brotherhoodxbusiness.com",
            "phone": "+447398341009",
            "whatsapp": "+447398341009",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "attending-next-event, speaker - bali, gia-8, feedback 2, gia-16-buyer, fb05, lead - community signup, member, gia-17-buyer",
            "ghl_contact_id": "G2PlgtpGDcu9gs9OT6IP",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "sarah simpson",
            "email": "siycoaching.co@gmail.com",
            "phone": "+17747225544",
            "whatsapp": "+17747225544",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "speaker - bali, gia-10-buyer, gia-11-buyer, founders_breakfast, gia-12-buyer, fb02, gia-13-buyer, women, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "JxhmA3v1vW51aViDNBYh",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "savina nikolova",
            "email": "savinanikolova@icloud.com",
            "phone": "+447904483695",
            "whatsapp": "+447904483695",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-10-buyer, women, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "Yim0xxbHx4TC8d45Xh8F",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "sim khela",
            "email": "sim@excellenceconsulting.co",
            "phone": "+6281239363759",
            "whatsapp": "+6281239363759",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-17-buyer, attending-next-event, fb06, lead - community signup, member, profile-complete",
            "ghl_contact_id": "FQBGoLf1QZGxl21k7Uc4",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "theo van dort",
            "email": "theo@brotherhoodblueprint.com",
            "phone": "+6288231690084",
            "whatsapp": "+6288231690084",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-5-buyer, priority audit, email bounced, gia-10-buyer, gia-11-buyer, gia-13-buyer, gia-15-buyer, feedback 2, founders_breakfast, lead - community signup, member, profile-complete, gia-16-buyer, gia-17-buyer, attending-next-event",
            "ghl_contact_id": "xxjOW3SdEr1okOXzRsHb",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "zac spowart",
            "email": "hello@zacspowart.com",
            "phone": "+13108667935",
            "whatsapp": "+13108667935",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-13-buyer, speaker - bali, gia-17-buyer, attending-next-event, lead - community signup, member, profile-complete",
            "ghl_contact_id": "k5X2tkhzmjrj1OWIEL2Z",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          }
        ],
        "unassigned_guests": [],
        "buyer_count": 44,
        "guest_slots_total": 2,
        "guests_booked": 2,
        "headcount": 46,
        "manual_adjustment_total": 0,
        "manual_adjustments": [],
        "override_delta": 0
      },
      "manual_adjustment_total": 0,
      "manual_adjustments": [],
      "guest_slot_override_delta": 0,
      "extra_tickets_total": 2
    },
    {
      "key": "fb",
      "name": "Founders Breakfast",
      "date": "2026-08-25",
      "tag": "fb06",
      "tiers": [
        {
          "tag": "fb06",
          "label": "Single",
          "tickets_per_contact": 1,
          "buyers": 2,
          "tickets": 2
        },
        {
          "tag": "fb06+1",
          "label": "+1 (2 tickets)",
          "tickets_per_contact": 2,
          "buyers": 0,
          "tickets": 0
        }
      ],
      "both_buyers": 6,
      "tickets_total": 8,
      "buyers_total": 8,
      "total_paid": 637.0,
      "csv": "fb-attendees.csv",
      "roster": null,
      "manual_adjustment_total": 0,
      "manual_adjustments": [],
      "guest_slot_override_delta": 0,
      "extra_tickets_total": 0
    }
  ],
  "both_tag": "gia17+fb06",
  "both_count": 6,
  "both_total_paid": 338.0,
  "both_csv": "both-events.csv",
  "stripe_enabled": true,
  "errors": [],
  "last_updated_iso": "2026-08-20T06:34:22.637644+00:00",
  "last_updated_local": "Thu 20 Aug 2026, 02:34 PM"
};
