window.dashboardData = {
  "events": [
    {
      "key": "gia",
      "name": "GIVE IT ALL",
      "date": "2026-06-25",
      "tag": "gia-15-buyer",
      "tiers": [
        {
          "tag": "gia-15-buyer",
          "label": "Single",
          "tickets_per_contact": 1,
          "buyers": 38,
          "tickets": 38
        },
        {
          "tag": "gia-15-4pack",
          "label": "4-Pack",
          "tickets_per_contact": 4,
          "buyers": 2,
          "tickets": 8
        }
      ],
      "both_buyers": 3,
      "tickets_total": 56,
      "buyers_total": 43,
      "total_paid": 1598.6,
      "csv": "gia-attendees.csv",
      "roster": {
        "buyers": [
          {
            "role": "Buyer",
            "name": "amy schwab",
            "email": "amyschwab2013@gmail.com",
            "phone": "+15305740102",
            "whatsapp": "+15305740102",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "speaker - bali, gia-9-buyer, gia-10-buyer, feedback 2, gia-14-buyer, women, gia-15-buyer, gia-4 ticket package, gia-15-4pack, lead - community signup, member, profile-complete",
            "ghl_contact_id": "xnJRXN7d2lP2rKGTkM5B",
            "tier": "4-Pack",
            "tickets": 4,
            "guest_capacity": 3,
            "guests": [
              {
                "role": "Guest",
                "name": "camie del carpio",
                "email": "camiedelcarpio2@gmail.com",
                "phone": "+6282266446155",
                "whatsapp": "+6282266446155",
                "attendee_type": "Guest",
                "booked_by": "amyschwab2013@gmail.com",
                "guest_of": "Amy Schwab",
                "booked": true,
                "profile": true,
                "member": true,
                "tags": "gia-15-guest, profile-complete, member",
                "ghl_contact_id": "rzo9y9O9T8TgGzmoUxDS"
              },
              {
                "role": "Guest",
                "name": "monika purba",
                "email": "purbamonika610@gmail.com",
                "phone": "+6285761247593",
                "whatsapp": "+6285761247593",
                "attendee_type": "Guest",
                "booked_by": "amyschwab2013@gmail.com",
                "guest_of": "Amy Schwab",
                "booked": true,
                "profile": true,
                "member": true,
                "tags": "gia-15-guest, lead - community signup, member, profile-complete",
                "ghl_contact_id": "YFpC5CSvb8jOYmlW2zuV"
              },
              {
                "role": "Guest",
                "name": "dan holloway",
                "email": "dan@scrapthe9to5.com",
                "phone": "+447828790759",
                "whatsapp": "+447828790759",
                "attendee_type": "Guest",
                "booked_by": "amyschwab2013@gmail.com",
                "guest_of": "Amy Schwab",
                "booked": true,
                "profile": false,
                "member": false,
                "tags": "gia-4-buyer, speaker - bali, gia-7-buyer, gia-9-buyer, archetypequizcompleted, archetype_freedomfortress, email bounced, feedback 2, founders_breakfast, gia-12-buyer, gia-14-buyer, gia-15-guest, lead - community signup",
                "ghl_contact_id": "7HDunMyvA7WVpGjRdOP5"
              }
            ],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "grace yeo",
            "email": "hello.gracexuann@gmail.com",
            "phone": "+6285333148049",
            "whatsapp": "+6285333148049",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-7-buyer, speaker - bali, gia-8-buyer, women, gia-15-buyer, gia-bali, gia-15-4pack, lead - community signup, member, profile-complete",
            "ghl_contact_id": "DLcbIgaAzuv7vslvANaN",
            "tier": "4-Pack",
            "tickets": 4,
            "guest_capacity": 8,
            "slot_override": true,
            "slot_override_note": "Speaker (own seat) + 2x 4-pack = 8 guest seats",
            "guests": [
              {
                "role": "Guest",
                "name": "melissa lambour",
                "email": "me@melissalambour.com",
                "phone": "+17329863319",
                "whatsapp": "+17329863319",
                "attendee_type": "Guest",
                "booked_by": "hello.gracexuann@gmail.com",
                "guest_of": "Grace Yeo",
                "booked": true,
                "profile": false,
                "member": false,
                "tags": "gia-15-guest",
                "ghl_contact_id": "gltynO6isYYIEsGkIBa8"
              },
              {
                "role": "Guest",
                "name": "karunia maulida",
                "email": "kapumali97@gmail.com",
                "phone": "+6285746835900",
                "whatsapp": "+6285746835900",
                "attendee_type": "Guest",
                "booked_by": "hello.gracexuann@gmail.com",
                "guest_of": "",
                "booked": true,
                "profile": false,
                "member": false,
                "tags": "gia-15-guest",
                "ghl_contact_id": "Qmp1Ay3lIHlslxKJkK4m"
              },
              {
                "role": "Guest",
                "name": "eli tham",
                "email": "test@testing.com",
                "phone": "+64275259987",
                "whatsapp": "+64275259987",
                "attendee_type": "Guest",
                "booked_by": "hello.gracexuann@gmail.com",
                "guest_of": "Grace Yeo",
                "booked": true,
                "profile": false,
                "member": false,
                "tags": "gia-15-guest",
                "ghl_contact_id": "tz4HCDySnaKvuhnbEGUZ"
              },
              {
                "role": "Guest",
                "name": "mike logan",
                "email": "mikeloganfit@gmail.com",
                "phone": "+16263929667",
                "whatsapp": "+16263929667",
                "attendee_type": "Guest",
                "booked_by": "hello.gracexuann@gmail.com",
                "guest_of": "Grace Yeo",
                "booked": true,
                "profile": true,
                "member": true,
                "tags": "gia-15-guest, profile-complete, member",
                "ghl_contact_id": "77jvHrRhsFryqw3endX4"
              },
              {
                "role": "Guest",
                "name": "rama -",
                "email": "ramadita.adi.pratama@gmail.com",
                "phone": "+6285935399333",
                "whatsapp": "+6285935399333",
                "attendee_type": "Guest",
                "booked_by": "hello.gracexuann@gmail.com",
                "guest_of": "Grace Yeo",
                "booked": true,
                "profile": false,
                "member": false,
                "tags": "gia-15-guest",
                "ghl_contact_id": "fvhKBRRLRH1JcL2eVl1p"
              },
              {
                "role": "Guest",
                "name": "gary sarco",
                "email": "gary.sarco@gmail.com",
                "phone": "+622402429859",
                "whatsapp": "+622402429859",
                "attendee_type": "Guest",
                "booked_by": "hello.gracexuann@gmail.com",
                "guest_of": "Grace Yeo",
                "booked": true,
                "profile": true,
                "member": true,
                "tags": "profile-complete, fb02, gia-15-guest, member",
                "ghl_contact_id": "gnYWngtVbCGCzPkLHl8Q"
              },
              {
                "role": "Guest",
                "name": "jessie chiang",
                "email": "hello@jessiechiang.com",
                "phone": "+19497489629",
                "whatsapp": "+19497489629",
                "attendee_type": "Guest",
                "booked_by": "hello.gracexuann@gmail.com",
                "guest_of": "Grace Yeo",
                "booked": true,
                "profile": true,
                "member": false,
                "tags": "gia-15-guest, profile-complete",
                "ghl_contact_id": "g8ZDFWj00ORu4nyiv0F7"
              },
              {
                "role": "Guest",
                "name": "sher s",
                "email": "imsuperiknow@gmail.com",
                "phone": "+6287874687491",
                "whatsapp": "+6287874687491",
                "attendee_type": "Guest",
                "booked_by": "hello.gracexuann@gmail.com",
                "guest_of": "Grace Yeo",
                "booked": true,
                "profile": true,
                "member": true,
                "tags": "gia-15-guest, profile-complete, member",
                "ghl_contact_id": "umGea69lNnnf60myRe1n"
              }
            ],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "brian siegal",
            "email": "briannathan545@gmail.com",
            "phone": "+17475772791",
            "whatsapp": "+17475772791",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "speaker - bali, gia-15-buyer, lead - community signup, member",
            "ghl_contact_id": "38PnoNIjkwWKPEXEvdFg",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "cath slater",
            "email": "cath@hirodrinks.com",
            "phone": "+6281238481980",
            "whatsapp": "+6281238481980",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-13-buyer, speaker - bali, gia-14-buyer, fb03, women, gia-15-buyer, lead - community signup, member, profile-complete",
            "ghl_contact_id": "YBA6sT6WR8LMFTYMKsLf",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "celine nysted",
            "email": "celine.nysted.co@gmail.com",
            "phone": "+4799355011",
            "whatsapp": "+4799355011",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "profile-complete, gia-15-buyer, member",
            "ghl_contact_id": "B8OgxULT87GBsXaxDCOe",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "chetan nandakumar",
            "email": "chetan.nandakumar@gmail.com",
            "phone": "+13025280208",
            "whatsapp": "+13025280208",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-14-buyer, fb03, gia-15-buyer, lead - community signup, member, profile-complete",
            "ghl_contact_id": "n9FuVQ255rn0xJ6uX2ZK",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "daria topic",
            "email": "topic.d@hotmail.hu",
            "phone": "+447707968481",
            "whatsapp": "+447707968481",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "speaker - bali, women, gia-15-buyer, lead - community signup, member, profile-complete",
            "ghl_contact_id": "GM4BmHakJ5a7Dubyt6V5",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "denise hager",
            "email": "hidenisehager@gmail.com",
            "phone": "+6285190594182",
            "whatsapp": "+6285190594182",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-12-buyer, gia-13-buyer, gia-14-buyer, lead - community signup, member, speaker - bali, women, gia-15-buyer",
            "ghl_contact_id": "tiLC4FOV9wPzfVYvjTzP",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "ellie keates",
            "email": "elliekeates@hotmail.com",
            "phone": "+447904812092",
            "whatsapp": "+447904812092",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-15-buyer",
            "ghl_contact_id": "N0omuJA8CLdh4rBfGypW",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "elliye gold",
            "email": "gjgd0926@gmail.com",
            "phone": "+628176404145",
            "whatsapp": "+628176404145",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-15-buyer",
            "ghl_contact_id": "1pnQceeITlfv4hNqUG5y",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "enes alili",
            "email": "enes.alili@hotmail.de",
            "phone": "+491623424065",
            "whatsapp": "+491623424065",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-15-buyer, lead - community signup, member, profile-complete",
            "ghl_contact_id": "XB0t7SKETgc1tjXGOkNO",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "farit surya",
            "email": "farit@houseofyoreh.com",
            "phone": "+6281289588882",
            "whatsapp": "+6281289588882",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-13-buyer, gia-15-buyer",
            "ghl_contact_id": "waXjbqmjmpj4Cp1CxhFu",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 1,
            "guests": [
              {
                "role": "Guest",
                "name": "Farit Surya +1",
                "email": "",
                "phone": "",
                "whatsapp": "",
                "attendee_type": "",
                "booked_by": "",
                "guest_of": "farit surya",
                "booked": true,
                "profile": false,
                "member": false,
                "tags": "manual-extra-guest",
                "ghl_contact_id": ""
              }
            ],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "jessica seruno",
            "email": "jessica.seruno@gmail.com",
            "phone": "+33646414880",
            "whatsapp": "+33646414880",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-15-buyer",
            "ghl_contact_id": "XDLeah9za3k5xYIx2zUd",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "job baltes",
            "email": "baltesjob@gmail.com",
            "phone": "+31637219162",
            "whatsapp": "+31637219162",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-12-buyer, founders_breakfast, speaker - bali, gia-13-buyer, fb02, lead - community signup, member, gia-14-buyer, fb03, gia15+fb04, gia-15-buyer, fb04",
            "ghl_contact_id": "jqAxFdk7W7YxEZvX7gGh",
            "tier": "Bundle (Both Events)",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "jordi marin",
            "email": "jmv.jordi@gmail.com",
            "phone": "+34630615757",
            "whatsapp": "+34630615757",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-6-buyer, fulfillment alignment, speaker - bali, gia-8-buyer, gia-9-buyer, archetypequizcompleted, archetype_freedomfortress, mens work, reconnected man, gia-10-buyer, feedback received, founders_breakfast, gia-12-buyer, gia-13-buyer, member, profile-complete, gia-14-buyer, gia-15-buyer",
            "ghl_contact_id": "0TbaMhgiEPT0fkSoLRSn",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "julia wimmer",
            "email": "juliaw1996@web.de",
            "phone": "+4915789660579",
            "whatsapp": "+4915789660579",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-15-buyer, lead - community signup, member, profile-complete",
            "ghl_contact_id": "uHjdn2xGo1T2tMMDFoTa",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "july achumbre",
            "email": "julyanne.achumbre@gmail.com",
            "phone": "+639982452937",
            "whatsapp": "+639982452937",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-15-buyer, lead - community signup, member, profile-complete, fb04",
            "ghl_contact_id": "ZT3n9wXKjgreSbOXvVap",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "klaudia grzelka",
            "email": "klaudiag206@gmail.com",
            "phone": "+447563941847",
            "whatsapp": "+447563941847",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-13-buyer, lead - community signup, member, gia-14-buyer, women, gia-15-buyer",
            "ghl_contact_id": "GiQVyGoYjqZZ7wjO0DuR",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "laura-marie casey",
            "email": "lauramarie.casey@icloud.com",
            "phone": "+34663984740",
            "whatsapp": "+34663984740",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "women, gia-15-buyer, lead - community signup, member, profile-complete",
            "ghl_contact_id": "Hg4uwCurcBWOEnewG40a",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "lukas seerup",
            "email": "lukas@wearespace.dk",
            "phone": "+628113703215",
            "whatsapp": "+628113703215",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-15-buyer, fb04",
            "ghl_contact_id": "PdAvLes6EXuSJmYBpHfv",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "luke smith",
            "email": "luke.c.smith93@gmail.com",
            "phone": "+61466168627",
            "whatsapp": "+61466168627",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "mens work, archetypequizcompleted, archetype_freedomfortress, speaker - bali, gia-14-buyer, gia-15-buyer, lead - community signup, member, profile-complete",
            "ghl_contact_id": "rNVJZmxchC9LtNXdz0Qy",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "magnus davies",
            "email": "magnusdavies1@hotmail.com",
            "phone": "+628214099040",
            "whatsapp": "+628214099040",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-15-buyer",
            "ghl_contact_id": "7ueqUYZxqv4VmoWIW2e9",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "martin lostak",
            "email": "martin.lostak.ai@gmail.com",
            "phone": "+436608383007",
            "whatsapp": "+436608383007",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-13-buyer, gia-15-buyer, lead - community signup, member, profile-complete",
            "ghl_contact_id": "WcEIdaLbGZVa9NWxJuKt",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "max greenhalgh",
            "email": "maxgreenhalgh.work@gmail.com",
            "phone": "+447473499596",
            "whatsapp": "+447473499596",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-15-buyer, lead - community signup, member",
            "ghl_contact_id": "GWfvV2FNMU7pQZZ2obHo",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "michelle maukner",
            "email": "mauknermichelle@gmail.com",
            "phone": "+447478950763",
            "whatsapp": "+447478950763",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-9-buyer, archetypequizcompleted, archetype_freedomfortress, mens work, unsubscribed, speaker - bali, gia-10-buyer, feedback received, women, gia-15-buyer",
            "ghl_contact_id": "WWvDqzOJByRnSP5E2C2z",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "mike mataraza",
            "email": "mike@coachwithmike.com",
            "phone": "+19492783436",
            "whatsapp": "+19492783436",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "reflection-ready, profile-complete, member, gia-14-buyer, gia14+fb03, speaker - bali, gia-15-buyer, fb04",
            "ghl_contact_id": "bjodhn9jhfBv9xx0iHr4",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "mitchell o'callaghan",
            "email": "mitchhaydenocallaghan@gmail.com",
            "phone": "+447794118543",
            "whatsapp": "+447794118543",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-15-buyer, profile-complete, member",
            "ghl_contact_id": "cyIDTYuwKgvWw8NUPuGX",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "nandar matari",
            "email": "nandar@matarimeditations.com",
            "phone": "+41764739802",
            "whatsapp": "+41764739802",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "unsubscribed, gia-12-buyer, speaker - bali, gia-14-buyer, lead - community signup, member, gia-15-buyer, profile-complete",
            "ghl_contact_id": "MprWUkAoitmPFb9dCFuZ",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "nikol toncheva",
            "email": "nikol.toncheva15@gmail.com",
            "phone": "+6282147387279",
            "whatsapp": "+6282147387279",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-15-buyer, lead - community signup, member",
            "ghl_contact_id": "Qp8RL9VcKL0p6mNym2wq",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "peter meglis",
            "email": "mailmeglis@gmail.com",
            "phone": "+19787585623",
            "whatsapp": "+19787585623",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "profile-complete, member, gia-14-buyer, gia-15-buyer",
            "ghl_contact_id": "SgGyjE5vQMQUjoDOmVMw",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "phillipa perel",
            "email": "hej@adhdsundhed.dk",
            "phone": "+4553535354",
            "whatsapp": "+4553535354",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-14-buyer, lead - community signup, member, profile-complete, gia-15-buyer, gia15+fb04, fb04, women, opted-in newsletter",
            "ghl_contact_id": "Rd38o7YtwpSmza44o9I0",
            "tier": "Bundle (Both Events)",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "pitria yulina",
            "email": "linna.cahaya@gmail.com",
            "phone": "+6281239044867",
            "whatsapp": "+6281239044867",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-6-buyer, women, gia-15-buyer",
            "ghl_contact_id": "D2b6AvxWrh7VCtARaTNP",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "robert hangu",
            "email": "robert.hangu@gmail.com",
            "phone": "+34602441540",
            "whatsapp": "+34602441540",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "member, profile-complete, lead - community signup, speaker - bali, gia-14-buyer, gia-15-buyer",
            "ghl_contact_id": "ITcKTNMqscUVvET3L9C7",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "ryan nurse",
            "email": "info@ryannurse.com",
            "phone": "+447784855040",
            "whatsapp": "+447784855040",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-14-buyer, lead - community signup, member, profile-complete, gia-15-buyer",
            "ghl_contact_id": "vsBTkrVqrrwWsYILMWku",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "sam dignan",
            "email": "dignan.samuel@gmail.com",
            "phone": "+61457866591",
            "whatsapp": "+61457866591",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-1-buyer, gia-2-buyer, speaker - bali, gia-5-buyer, gia-7-buyer, gia-15-buyer, gia-14-buyer",
            "ghl_contact_id": "9wvNqYieCj19RbN7ychJ",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "samira sandner",
            "email": "private@samirasandner.com",
            "phone": "+61472797149",
            "whatsapp": "+61472797149",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-15-buyer, lead - community signup, member",
            "ghl_contact_id": "sPkRx3yTxKKFH9tdCvmq",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "serena spink",
            "email": "serena_spink@hotmail.co.uk",
            "phone": "+447511404769",
            "whatsapp": "+447511404769",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-15-buyer, gia15+fb04, fb04, lead - community signup, member, profile-complete",
            "ghl_contact_id": "ElNGRtO2LLnf8b4qfgyF",
            "tier": "Bundle (Both Events)",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "shari van de craen",
            "email": "hello@sharivandecraen.com",
            "phone": "+32470552027",
            "whatsapp": "+32470552027",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-10-buyer, speaker - bali, women, gia-12-buyer, gia-15-buyer, lead - community signup, member, profile-complete",
            "ghl_contact_id": "PDBFXKDBqx2UzNIL1Un7",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "sophia fox",
            "email": "sophlfox@outlook.com",
            "phone": "+13604864500",
            "whatsapp": "+13604864500",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-4 ticket package, gia-14-buyer, speaker - bali, women, gia-15-buyer",
            "ghl_contact_id": "aIULpGiRMOU9o31PeNR8",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "taryn j young",
            "email": "tarynyoung91@gmail.com",
            "phone": "+62466465181",
            "whatsapp": "+62466465181",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "speaker - bali, gia-2-buyer, feedback received, gia-11-buyer, women, lead - community signup, member, gia-15-buyer",
            "ghl_contact_id": "SpiCyfYXnDPf2A6K44dT",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "teodora dimitrova koleva",
            "email": "teodora.koleva7b@gmail.com",
            "phone": "+359894858540",
            "whatsapp": "+359894858540",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": false,
            "tags": "gia-15-buyer",
            "ghl_contact_id": "1VpC9WjYgb4HJ5yisYKe",
            "tier": "Single",
            "tickets": 2,
            "guest_capacity": 1,
            "guests": [
              {
                "role": "Guest",
                "name": "teodora dimitrova koleva (+1)",
                "email": "",
                "phone": "",
                "whatsapp": "",
                "attendee_type": "",
                "booked_by": "",
                "guest_of": "teodora dimitrova koleva",
                "booked": true,
                "profile": false,
                "member": false,
                "tags": "extra-ticket",
                "ghl_contact_id": ""
              }
            ],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "theo van dort",
            "email": "theo@brotherhoodblueprint.com",
            "phone": "+447836343458",
            "whatsapp": "+447836343458",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": true,
            "member": true,
            "tags": "gia-5-buyer, priority audit, email bounced, gia-10-buyer, gia-11-buyer, gia-13-buyer, gia-15-buyer, feedback 2, founders_breakfast, lead - community signup, member, profile-complete",
            "ghl_contact_id": "xxjOW3SdEr1okOXzRsHb",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          },
          {
            "role": "Buyer",
            "name": "veny lydiawati",
            "email": "vestudesign@gmail.com",
            "phone": "+6281380285725",
            "whatsapp": "+6281380285725",
            "attendee_type": "",
            "booked_by": "",
            "guest_of": "",
            "booked": true,
            "profile": false,
            "member": true,
            "tags": "gia-10-buyer, women, gia-15-buyer, lead - community signup, member",
            "ghl_contact_id": "Rr3B6oLHOiKkAD1tJDCg",
            "tier": "Single",
            "tickets": 1,
            "guest_capacity": 0,
            "guests": [],
            "open_slots": 0
          }
        ],
        "unassigned_guests": [],
        "buyer_count": 43,
        "guest_slots_total": 13,
        "guests_booked": 13,
        "headcount": 56,
        "manual_adjustment_total": 0,
        "manual_adjustments": [],
        "override_delta": 5
      },
      "manual_adjustment_total": 0,
      "manual_adjustments": [],
      "guest_slot_override_delta": 5,
      "extra_tickets_total": 2
    },
    {
      "key": "fb",
      "name": "Founders Breakfast",
      "date": "2026-06-30",
      "tag": "fb04",
      "tiers": [
        {
          "tag": "fb04",
          "label": "Single",
          "tickets_per_contact": 1,
          "buyers": 8,
          "tickets": 8
        },
        {
          "tag": "fb04+1",
          "label": "+1 (2 tickets)",
          "tickets_per_contact": 2,
          "buyers": 0,
          "tickets": 0
        }
      ],
      "both_buyers": 3,
      "tickets_total": 11,
      "buyers_total": 11,
      "total_paid": 492.5,
      "csv": "fb-attendees.csv",
      "roster": null,
      "manual_adjustment_total": 0,
      "manual_adjustments": [],
      "guest_slot_override_delta": 0,
      "extra_tickets_total": 0
    }
  ],
  "both_tag": "gia15+fb04",
  "both_count": 3,
  "both_total_paid": 101.0,
  "both_csv": "both-events.csv",
  "stripe_enabled": true,
  "errors": [],
  "last_updated_iso": "2026-06-29T02:09:24.956806+00:00",
  "last_updated_local": "Mon 29 Jun 2026, 10:09 AM"
};
